apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-rs
  labels:
    app: langgraph-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: langgraph-rs
  template:
    metadata:
      labels:
        app: langgraph-rs
    spec:
      containers:
      - name: langgraph-rs
        image: langgraph-rs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: RUST_LOG
          value: "info"
        - name: RUST_BACKTRACE
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
