apiVersion: v1
kind: Service
metadata:
  name: langgraph-rs
  labels:
    app: langgraph-rs
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: langgraph-rs
